### ISSUE TITLE
FilePicker crashing only on API 29

### ISSUE THREAD

**Issue by Row7** [miguelpruivo/plugins_flutter_file_picker#94]
Hello, my program is crashing when I select an audio file on API 29. It works fine with API 28 and lower versions.

pubspec: `file_picker: ^1.3.5`

Im using this line to open the file picker and I have not any problem until API 29:

`File file = await FilePicker.getFile(type: FileType.AUDIO);`

I tried with file names without special characters and changing FileType to FileType.ANY but it didn't work.

Crash log:

`--------- beginning of crash
2019-06-15 22:01:31.200 9319-9319/com.testapp.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testapp.app, PID: 9319
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=47445, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/msf:253 flg=0x1 }} to activity {com.testapp.app/com.example.app.MainActivity}: java.lang.NumberFormatException: For input string: "msf:253"
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4830)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4871)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
     Caused by: java.lang.NumberFormatException: For input string: "msf:253"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.valueOf(Long.java:808)
        at com.mr.flutter.plugin.filepicker.FileUtils.getForApi19(FileUtils.java:73)
        at com.mr.flutter.plugin.filepicker.FileUtils.getPath(FileUtils.java:33)
        at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:78)
        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:222)
        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:142)
        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
        at android.app.Activity.dispatchActivityResult(Activity.java:8091)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4823)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4871) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7319) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934) `

Any idea?

**Comment by miguelpruivo** [comment]
Hi, there’s no support yet for api 29 in the package, since api 29 is in a beta stage. The maximum currently supported is the 28 or below. 

Thank you.

**Comment by Row7** [comment]
Thanks for your quick response, regards.
